<b>

<b>

<b>Project</b>
Buatlah data latihan sederhana untuk klasifikasi data berdasarkan
<ol>
    <li> usia : 18 - 60</li>
    <li> Transaksi perbulan : 0 - 50</li>
    <li> Label : Loyal(0), Tidak Loyal(1)</li>
    <li> gander : L , P</li>
</ol>

In [28]:
import numpy as np
import pandas as pd

n_data = 100

usia = np.random.randint(18,61,size=n_data)
transaksi = np.random.randint(0,51,size=n_data)
label = np.random.randint(0,2,size=n_data)
gander = np.random.choice(['L','P'],size=n_data)

df = pd.DataFrame({
    'Usia' : usia,
    'Transaksi' : transaksi,
    'label' : label,
    'Gender' : gander
    
})
df.to_csv('dataLatih.csv',index=False)
df.head #mengetahui 5 baris pertama dari dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Usia       100 non-null    int64
 1   Transaksi  100 non-null    int64
 2   label      100 non-null    int64
 3   Gender     100 non-null    object
dtypes: int64(3), object(1)
memory usage: 3.3+ KB

In [62]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

np.random.seed(42)

n = 10000

# Buat list tanggal acak langsung tanpa fungsi
start = datetime(2020, 1, 1)
end = datetime(2025, 1, 1)
start_u = start.timestamp()
end_u = end.timestamp()
timestamps = [datetime.fromtimestamp(random.uniform(start_u, end_u)) for _ in range(n)]

# Buat DataFrame simulasi data Bitcoin
df = pd.DataFrame({
    'timestamp': timestamps,
    'price_usd': np.round(np.random.uniform(10000, 70000, n), 2),
    'volume_btc': np.round(np.random.uniform(0.01, 100.0, n), 4),
    'market_cap_usd': np.round(np.random.uniform(1e9, 1.5e12, n), 2),
    'transactions': np.random.randint(50, 10000, n),
    'mining_difficulty': np.round(np.random.uniform(1e12, 3e13, n), 2),
    'hash_rate_ths': np.round(np.random.uniform(50000, 250000, n), 2),
    'fees_usd': np.round(np.random.uniform(0.1, 500.0, n), 2),
    'sentiment': np.random.choice(['Bullish', 'Bearish', 'Neutral'], n),
    'exchange': np.random.choice(['Indodax', 'Triv', 'Pintu', 'Pluang'], n)
})

# Urutkan berdasarkan waktu
df = df.sort_values('timestamp').reset_index(drop=True)

# Lihat 5 data pertama
df.head()

,timestamp,price_usd,volume_btc,market_cap_usd,transactions,mining_difficulty,hash_rate_ths,fees_usd,sentiment,exchange
0,2020-01-02 02:23:52.373455,67962.85,72.1937,1.119201e+12,9387,1.073353e+12,142803.69,424.19,Bullish,Indodax
1,2020-01-02 10:22:41.056719,40006.77,33.6145,2.689590e+11,3708,3.279620e+12,151385.91,19.22,Bearish,Pintu
2,2020-01-02 11:37:44.139494,60406.48,93.3531,1.468918e+12,7590,2.766568e+13,60166.45,433.41,Neutral,Pluang
3,2020-01-02 12:10:14.417359,64552.13,44.6777,8.986647e+11,113,2.791817e+13,169969.19,53.96,Bullish,Pintu
4,2020-01-02 15:19:45.520010,35565.00,47.5280,1.454416e+12,9190,3.749715e+12,148903.41,440.56,Neutral,Indodax